version: '3.9'

services:
  nestapp:
    container_name: tiendamia
    image: gmujica/tiendamia:1.0.0
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db 
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=tiendamia
      - PG_PORT=5432
    depends_on:
      - db
  db:
    container_name: tiendamia_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tiendamia
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}